# Generated by Django 3.1.4 on 2020-12-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.person'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.person'),
        ),
    ]
