# Generated by Django 3.1.4 on 2020-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201215_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='about_me',
            new_name='about_me_1',
        ),
        migrations.AddField(
            model_name='person',
            name='about_me_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
